# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnimeCharacters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AnimeCharacters
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'SwifterSwift'
  pod 'SwiftyJSON'

  target 'AnimeCharactersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimeCharactersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
